all: true
testonly: false
with-expecter: true
dir: tests/mocks/{{ replaceAll .InterfaceDirRelative "pkg" ""}}
outpkg: '{{.PackageName}}_mocks'
filename: '{{.InterfaceName | snakecase }}_mock.go'
packages:
  hex/mjolnir-core/pkg/interfaces:
    config:
      recursive: true
  hex/mjolnir-core/pkg/repositories:
    config:
      recursive: true
  hex/mjolnir-core/pkg/config:
    config:
      recursive: true
